(() => {
  if (window.__JOVELYA_A11Y_UX_INSTALLED__) return;
  window.__JOVELYA_A11Y_UX_INSTALLED__ = true;

  const copy = {
    fr: {
      skip: 'Aller au contenu principal', nav: 'Navigation principale', language: "Passer l’interface en arabe",
      fields: {
        regEmail:'E-mail',regPass:'Mot de passe',regInvite:"Code d’invitation",logEmail:'E-mail',logPass:'Mot de passe',cvTitle:'Nom du CV',cvRole:'Métier recherché',cvFullName:'Nom et prénom',cvPhone:'Téléphone',cvEmail:'E-mail du CV',cvAddress:'Ville / Adresse',cvProfile:'Profil professionnel',cvExperience:'Expériences',cvSkills:'Compétences',cvEducation:'Formation / Études',cvLanguages:'Langues',letterTitle:'Titre de la lettre',letterCompany:'Entreprise',letterRole:'Poste',letterContent:'Contenu de la lettre',appCompany:'Entreprise',appRole:'Poste',appStatus:'Statut de la candidature',appDate:'Date de candidature',appNotes:'Notes',atsCv:'CV à analyser',atsOffer:"Offre d’emploi",interviewRole:'Poste visé',fbRating:'Note',fbCategory:'Catégorie',fbMessage:'Votre retour',resetNewPassword:'Nouveau mot de passe',resetConfirmPassword:'Confirmer le mot de passe'
      }
    },
    ar: {
      skip:'الانتقال إلى المحتوى الرئيسي',nav:'التنقل الرئيسي',language:'تحويل الواجهة إلى الفرنسية',
      fields:{regEmail:'البريد الإلكتروني',regPass:'كلمة المرور',regInvite:'رمز الدعوة',logEmail:'البريد الإلكتروني',logPass:'كلمة المرور',cvTitle:'اسم السيرة الذاتية',cvRole:'الوظيفة المطلوبة',cvFullName:'الاسم الكامل',cvPhone:'الهاتف',cvEmail:'البريد الإلكتروني في السيرة الذاتية',cvAddress:'المدينة / العنوان',cvProfile:'الملف المهني',cvExperience:'الخبرات',cvSkills:'المهارات',cvEducation:'الدراسة / التكوين',cvLanguages:'اللغات',letterTitle:'عنوان رسالة التقديم',letterCompany:'الشركة',letterRole:'المنصب',letterContent:'محتوى رسالة التقديم',appCompany:'الشركة',appRole:'المنصب',appStatus:'حالة طلب العمل',appDate:'تاريخ طلب العمل',appNotes:'ملاحظات',atsCv:'السيرة الذاتية للتحليل',atsOffer:'إعلان الوظيفة',interviewRole:'الوظيفة المطلوبة',fbRating:'التقييم',fbCategory:'الفئة',fbMessage:'ملاحظتك',resetNewPassword:'كلمة المرور الجديدة',resetConfirmPassword:'تأكيد كلمة المرور'}
    }
  };
  const language=()=>document.documentElement.lang==='ar'?'ar':'fr',text=()=>copy[language()],byId=id=>document.getElementById(id);
  const style=document.createElement('style');style.id='jovelyaAccessibilityUxStyles';style.textContent='.jovelya-skip-link{position:fixed;z-index:10000;top:8px;inset-inline-start:12px;padding:10px 14px;border-radius:9px;background:#fff;color:#111827;font-weight:800;text-decoration:none;transform:translateY(-180%);transition:transform .12s ease}.jovelya-skip-link:focus{transform:translateY(0)}.jovelya-sr-only{position:absolute!important;width:1px!important;height:1px!important;padding:0!important;margin:-1px!important;overflow:hidden!important;clip:rect(0 0 0 0)!important;white-space:nowrap!important;border:0!important}:where(button,a[href],input,textarea,select,[role="button"],[tabindex]):focus-visible{outline:3px solid #fff!important;outline-offset:2px!important;box-shadow:0 0 0 5px #0b67e8!important}@media(prefers-reduced-motion:reduce){*,*::before,*::after{scroll-behavior:auto!important;animation-duration:.01ms!important;animation-iteration-count:1!important;transition-duration:.01ms!important}}';document.head.appendChild(style);
  const main=document.querySelector('main');if(main){main.id=main.id||'main-content';if(!main.hasAttribute('tabindex'))main.tabIndex=-1;}
  let skip=document.querySelector('.jovelya-skip-link');if(!skip&&main){skip=document.createElement('a');skip.className='jovelya-skip-link';skip.href='#'+main.id;skip.addEventListener('click',()=>setTimeout(()=>main.focus({preventScroll:true}),0));document.body.insertAdjacentElement('afterbegin',skip);}
  const nav=document.querySelector('.nav');const navTargets={navHome:'home',navAccount:'account',navCv:'cv',navLetters:'letters',navApps:'apps',navAts:'ats',navInterview:'interview',navFeedback:'feedback'};if(nav)nav.setAttribute('role','navigation');
  function ensureRegions(){document.querySelectorAll('main > section').forEach((section,index)=>{const heading=section.querySelector('h1,h2,h3');if(!heading)return;if(!heading.id)heading.id='sectionHeading'+index;section.setAttribute('aria-labelledby',heading.id);});const ats=byId('atsResult');if(ats){ats.setAttribute('role','region');ats.setAttribute('aria-live','polite');}const interview=byId('interviewResult');if(interview){interview.setAttribute('role','region');interview.setAttribute('aria-live','polite');}}
  function fieldName(control){const known=text().fields[control.id];if(known)return known;const placeholder=String(control.getAttribute('placeholder')||'').trim();if(placeholder)return placeholder;const emptyOption=control.tagName==='SELECT'?control.querySelector('option[value=""]'):null;if(emptyOption&&emptyOption.textContent.trim())return emptyOption.textContent.trim();const title=String(control.getAttribute('title')||'').trim();if(title)return title;const id=String(control.id||control.name||'').replace(/([a-z])([A-Z])/g,'$1 $2').replace(/[-_]+/g,' ').trim();return language()==='ar'?('حقل '+(id||'إدخال')):('Champ '+(id||'de saisie'));}
  function hasName(control){return !!((control.labels&&control.labels.length)||String(control.getAttribute('aria-label')||'').trim()||String(control.getAttribute('aria-labelledby')||'').trim());}
  // Known fields retain explicit labels even when legacy localization runs first.
  function ensureControlName(control){if(!(control instanceof HTMLElement)||control.matches('input[type="hidden"]')||control.hidden||(control.labels&&control.labels.length)||(!text().fields[control.id]&&hasName(control)))return;if(!control.id)control.id='a11yField'+Math.random().toString(36).slice(2,10);let label=document.querySelector('label[data-jovelya-a11y-for="'+CSS.escape(control.id)+'"]');if(!label){label=document.createElement('label');label.className='jovelya-sr-only';label.dataset.jovelyaA11yFor=control.id;label.htmlFor=control.id;control.insertAdjacentElement('beforebegin',label);}label.textContent=fieldName(control);}
  function refreshGeneratedLabels(){document.querySelectorAll('label[data-jovelya-a11y-for]').forEach(label=>{const control=byId(label.dataset.jovelyaA11yFor);if(control)label.textContent=fieldName(control);});}
  function enhanceControls(root=document){root.querySelectorAll?.('input,textarea,select').forEach(ensureControlName);[byId('regEmail'),byId('logEmail')].filter(Boolean).forEach(control=>{control.type='email';control.inputMode='email';control.autocomplete='email';});const regPass=byId('regPass');if(regPass)regPass.autocomplete='new-password';const logPass=byId('logPass');if(logPass)logPass.autocomplete='current-password';const invite=byId('regInvite');if(invite){invite.autocomplete='off';invite.spellcheck=false;}}
  function enhanceClickable(root=document){root.querySelectorAll?.('[onclick]').forEach(element=>{if(element.matches('button,a[href],input,select,textarea,summary')||element.classList.contains('stat'))return;if(element.getAttribute('role')||element.hasAttribute('tabindex'))return;element.setAttribute('role','button');element.tabIndex=0;element.dataset.jovelyaKeyboard='true';element.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();element.click();}});});}
  function syncNavigation(){const current=[...document.querySelectorAll('main > section')].find(section=>!section.classList.contains('hidden'))?.id||'home';document.querySelectorAll('.nav button').forEach(button=>{button.type='button';const target=navTargets[button.dataset.i18n];if(target)button.setAttribute('aria-controls',target);const active=target===current;button.classList.toggle('active-nav',active);if(active)button.setAttribute('aria-current','page');else button.removeAttribute('aria-current');});}
  function localize(){if(skip)skip.textContent=text().skip;if(nav)nav.setAttribute('aria-label',text().nav);const langButton=byId('langBtn');if(langButton)langButton.setAttribute('aria-label',text().language);refreshGeneratedLabels();syncNavigation();}
  const banner=byId('banner');if(banner){banner.setAttribute('role','status');banner.setAttribute('aria-live','polite');banner.setAttribute('aria-atomic','true');if(!banner.hasAttribute('tabindex'))banner.tabIndex=-1;}const health=byId('health');if(health){health.setAttribute('role','status');health.setAttribute('aria-live','polite');health.setAttribute('aria-atomic','true');}const toast=byId('cvfToast');if(toast)toast.setAttribute('aria-atomic','true');
  ensureRegions();enhanceControls();enhanceClickable();localize();if(main)new MutationObserver(syncNavigation).observe(main,{subtree:true,attributes:true,attributeFilter:['class']});new MutationObserver(()=>{enhanceControls();enhanceClickable();ensureRegions();}).observe(document.body,{subtree:true,childList:true});new MutationObserver(()=>setTimeout(localize,0)).observe(document.documentElement,{attributes:true,attributeFilter:['lang','dir']});
})();
