import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';
import { before, after, test } from 'node:test';
import { chromium } from 'playwright';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const origin='http://127.0.0.1:32211/';
let scratch,html,browser;
before(async()=>{
  scratch=fs.mkdtempSync(path.join(os.tmpdir(),'jovelya-accessibility-ux-'));
  for(const name of ['server','public','package.json','render.yaml'])fs.cpSync(path.join(root,name),path.join(scratch,name),{recursive:true});
  const normalize=dir=>{for(const entry of fs.readdirSync(dir,{withFileTypes:true})){const file=path.join(dir,entry.name);if(entry.isDirectory())normalize(file);else if(/\.(js|html|json|yaml)$/.test(file))fs.writeFileSync(file,fs.readFileSync(file,'utf8').replace(/\r\n/g,'\n'));}};
  normalize(scratch);const pkg=JSON.parse(fs.readFileSync(path.join(scratch,'package.json')));
  for(let pass=0;pass<2;pass++)for(const command of [pkg.scripts['prepatch:public'],...pkg.scripts['patch:public'].split(' && ')]){const r=spawnSync(process.execPath,[command.slice(5)],{cwd:scratch,encoding:'utf8'});assert.equal(r.status,0,r.stderr||r.stdout);}
  html=fs.readFileSync(path.join(scratch,'public/index.html'),'utf8');assert.equal(html.split('ACCESSIBILITY_UX_V1').length-1,1);
  browser=await chromium.launch({headless:true,...(process.env.PLAYWRIGHT_EXECUTABLE_PATH?{executablePath:process.env.PLAYWRIGHT_EXECUTABLE_PATH}:{})});
});
after(async()=>{await browser?.close();if(scratch)fs.rmSync(scratch,{recursive:true,force:true});});
async function fixture(language='fr',suffix=''){
  const context=await browser.newContext({serviceWorkers:'block',viewport:{width:375,height:800},reducedMotion:'reduce'}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.addInitScript(language=>localStorage.setItem('cvf_lang',language),language);
  await context.route('**/*',async route=>{const url=new URL(route.request().url());if(url.pathname==='/')return route.fulfill({contentType:'text/html',body:html.replace('<script>/* ACCESSIBILITY_UX_V1 */', '<script>syncApplicationI18n();</script><script>/* ACCESSIBILITY_UX_V1 */')});let body={ok:true};if(url.pathname==='/api/health')body={ok:true,version:'20.7.0'};else if(url.pathname==='/api/public/config')body={registration_mode:'open',billing_enabled:false,ai_enabled:false};else if(url.pathname==='/api/cvs')body={cvs:[]};else if(url.pathname==='/api/letters')body={letters:[]};else if(url.pathname==='/api/applications')body={applications:[]};else if(url.pathname==='/api/me')return route.fulfill({status:401,contentType:'application/json',body:'{"error":"not signed in"}'});return route.fulfill({contentType:'application/json',body:JSON.stringify(body)});});
  await page.goto(origin+suffix);await page.waitForFunction(()=>document.getElementById('jovelyaAccessibilityUxStyles'));return {page,async close(){await context.close();assert.deepEqual(errors,[]);}};
}
const fields=['regEmail','regPass','regInvite','logEmail','logPass','cvTitle','cvRole','cvFullName','cvPhone','cvEmail','cvAddress','cvProfile','cvExperience','cvSkills','cvEducation','cvLanguages','letterTitle','letterCompany','letterRole','letterContent','appCompany','appRole','appStatus','appDate','appNotes','atsCv','atsOffer','interviewRole','fbRating','fbCategory','fbMessage'];
for(const language of ['fr','ar'])test(`core fields and live regions are accessible (${language})`,async()=>{const f=await fixture(language);try{assert.equal(await f.page.locator('html').getAttribute('dir'),language==='ar'?'rtl':'ltr');assert.ok((await f.page.locator('.jovelya-skip-link').textContent()).trim());assert.ok((await f.page.locator('.nav').getAttribute('aria-label')).trim());assert.equal(await f.page.locator('#banner').getAttribute('aria-live'),'polite');assert.equal(await f.page.locator('#health').getAttribute('role'),'status');for(const id of fields){const label=f.page.locator('label[for="'+id+'"]');assert.equal(await label.count(),1,id);assert.ok((await label.textContent()).trim(),id);}const unnamed=await f.page.evaluate(()=>[...document.querySelectorAll('input,textarea,select')].filter(el=>el.type!=='hidden'&&!el.hidden&&!(el.labels&&el.labels.length)&&!String(el.getAttribute('aria-label')||'').trim()&&!String(el.getAttribute('aria-labelledby')||'').trim()).map(el=>el.id));assert.deepEqual(unnamed,[]);assert.equal(await f.page.locator('#regEmail').getAttribute('autocomplete'),'email');assert.equal(await f.page.locator('#regPass').getAttribute('autocomplete'),'new-password');assert.equal(await f.page.locator('#logPass').getAttribute('autocomplete'),'current-password');assert.ok(await f.page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}finally{await f.close();}});
test('keyboard navigation and current-page state stay reliable',async()=>{const f=await fixture();try{assert.equal(await f.page.locator('.nav button[data-i18n="navHome"]').getAttribute('aria-current'),'page');const stat=f.page.locator('#home .stat').first();await stat.focus();await f.page.keyboard.press('Enter');await f.page.waitForFunction(()=>!document.getElementById('cv').classList.contains('hidden'));await f.page.waitForFunction(()=>document.querySelector('.nav button[data-i18n="navCv"]').getAttribute('aria-current')==='page');const inaccessible=await f.page.evaluate(()=>[...document.querySelectorAll('[onclick]')].filter(el=>!el.matches('button,a[href],input,select,textarea,summary')&&!(el.getAttribute('role')==='button'&&el.tabIndex>=0)).map(el=>el.id));assert.deepEqual(inaccessible,[]);const home=f.page.locator('.nav button[data-i18n="navHome"]');await home.focus();const style=await home.evaluate(el=>({outline:getComputedStyle(el).outlineStyle,width:parseFloat(getComputedStyle(el).outlineWidth)}));assert.notEqual(style.outline,'none');assert.ok(style.width>=2);await f.page.locator('.jovelya-skip-link').focus();await f.page.keyboard.press('Enter');await f.page.waitForFunction(()=>document.activeElement===document.querySelector('main'));}finally{await f.close();}});
test('labels track language changes without duplication',async()=>{const f=await fixture();try{assert.equal((await f.page.locator('label[for="appStatus"]').textContent()).trim(),'Statut de la candidature');await f.page.locator('#langBtn').click();await f.page.waitForFunction(()=>document.documentElement.lang==='ar');await f.page.waitForFunction(()=>document.querySelector('label[for="appStatus"]').textContent.includes('حالة'));assert.equal(await f.page.locator('label[for="appStatus"]').count(),1);}finally{await f.close();}});
for(const language of ['fr','ar'])test(`password reset controls get labels (${language})`,async()=>{const f=await fixture(language,'?reset=synthetic-token');try{for(const id of ['resetNewPassword','resetConfirmPassword']){const label=f.page.locator('label[for="'+id+'"]');assert.equal(await label.count(),1,id);assert.ok((await label.textContent()).trim());}assert.equal(await f.page.locator('.nav button[data-i18n="navAccount"]').getAttribute('aria-current'),'page');}finally{await f.close();}});
