-- Fresh-database baseline derived from server/index.js, auth.js, auth-tokens.js
-- and the generated Jobs update route. Never apply blindly to an existing schema.
CREATE TABLE public.users (
 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 email text NOT NULL UNIQUE, password_hash text NOT NULL,
 plan text NOT NULL DEFAULT 'free', token_version integer NOT NULL DEFAULT 0,
 email_verified boolean NOT NULL DEFAULT false,
 stripe_customer_id text, stripe_subscription_id text, subscription_status text,
 created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX users_subscription_idx ON public.users(stripe_subscription_id);
CREATE TABLE public.profiles (
 user_id integer PRIMARY KEY REFERENCES public.users(id) ON DELETE CASCADE,
 data_json text NOT NULL DEFAULT '{}', updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE public.cv_documents (
 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_id integer NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
 title text NOT NULL, target_role text NOT NULL DEFAULT '', data_json text NOT NULL DEFAULT '{}',
 is_primary boolean NOT NULL DEFAULT false,
 created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX cvs_user_order_idx ON public.cv_documents(user_id,is_primary DESC,updated_at DESC,id DESC);
CREATE TABLE public.cover_letters (
 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_id integer NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
 title text NOT NULL, company text NOT NULL DEFAULT '', target_role text NOT NULL DEFAULT '', content text NOT NULL DEFAULT '',
 created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX letters_user_order_idx ON public.cover_letters(user_id,updated_at DESC,id DESC);
CREATE TABLE public.applications (
 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_id integer NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
 company text NOT NULL, role text NOT NULL, status text NOT NULL DEFAULT 'Envoyée',
 applied_date text NOT NULL DEFAULT '', notes text NOT NULL DEFAULT '',
 created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX applications_user_order_idx ON public.applications(user_id,id DESC);
CREATE TABLE public.password_reset_tokens (
 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_id integer NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
 token_hash text NOT NULL UNIQUE, expires_at timestamptz NOT NULL, used_at timestamptz
);
CREATE INDEX reset_tokens_user_idx ON public.password_reset_tokens(user_id);
CREATE TABLE public.email_verification_tokens (
 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_id integer NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
 token_hash text NOT NULL UNIQUE, expires_at timestamptz NOT NULL, used_at timestamptz
);
CREATE INDEX verification_tokens_user_idx ON public.email_verification_tokens(user_id);
CREATE TABLE public.ai_usage (
 user_id integer NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
 usage_date date NOT NULL, request_count integer NOT NULL DEFAULT 0,
 PRIMARY KEY(user_id,usage_date)
);
CREATE TABLE public.feedback (
 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_id integer REFERENCES public.users(id) ON DELETE SET NULL,
 rating integer, category text NOT NULL DEFAULT 'general', message text NOT NULL, page text NOT NULL DEFAULT '',
 status text NOT NULL DEFAULT 'open', admin_note text NOT NULL DEFAULT '',
 created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX feedback_user_idx ON public.feedback(user_id);
CREATE TABLE public.audit_log (
 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_id integer REFERENCES public.users(id) ON DELETE SET NULL,
 event_type text NOT NULL, event_data text NOT NULL DEFAULT '{}',
 created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX audit_user_idx ON public.audit_log(user_id);
CREATE TABLE public.client_errors (
 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_id integer REFERENCES public.users(id) ON DELETE SET NULL,
 message text NOT NULL, source text NOT NULL DEFAULT '', line integer, column_no integer,
 stack text NOT NULL DEFAULT '', page text NOT NULL DEFAULT '', user_agent text NOT NULL DEFAULT '',
 created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX client_errors_user_idx ON public.client_errors(user_id);
CREATE TABLE public.beta_invites (
 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 code text NOT NULL UNIQUE, label text NOT NULL DEFAULT '', max_uses integer NOT NULL DEFAULT 1,
 used_count integer NOT NULL DEFAULT 0, is_active boolean NOT NULL DEFAULT true,
 expires_at timestamptz, created_by integer REFERENCES public.users(id) ON DELETE SET NULL,
 created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX invites_creator_idx ON public.beta_invites(created_by);
CREATE TABLE public.beta_invite_uses (
 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 invite_id integer NOT NULL REFERENCES public.beta_invites(id),
 user_id integer NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
 used_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX invite_uses_invite_idx ON public.beta_invite_uses(invite_id);
CREATE INDEX invite_uses_user_idx ON public.beta_invite_uses(user_id);
